inherit_from:
 - .rubocop_todo.yml
 - .rubocop_cocoapods.yml

#- Core -----------------------------------------------------------------------

AllCops:
  Exclude:
    - spec/fixtures/**/*
    - lib/cocoapods-core/vendor/**/*
    - vendor/**/*

FileName:
  Exclude:
    - lib/cocoapods-core.rb

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
