# Offense count: 3
Lint/UselessAssignment:
  Enabled: false

# Offense count: 12
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 304

# Offense count: 10
Metrics/CyclomaticComplexity:
  Max: 11

# Offense count: 360
# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 175

# Offense count: 55
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 27

# Offense count: 8
Metrics/PerceivedComplexity:
  Max: 12

# Offense count: 5
# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/VariableName:
  Enabled: false

HashSyntax:
  EnforcedStyle: ruby19

Metrics/LineLength:
  Exclude:
    - spec/**/*