sudo: false
language: ruby
rvm: 2.4.0
cache: bundle
addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-server-dev-9.4
env:
  secure: "MeyjQ3gyQBQhvTxHC/HQSUG2LmvGdeD9aizM+pNxF8ae+0Rf4yPXKhJdQW8iNnl1QnQdNEHv/6y4mitR2UJ4wllSW/kvk6SBPQShXSmvrQIAX//R8hR4vZzRnLkEZmfL8al1ZazPABOeinQg6vEL1+AYjOLk2UAfHvcyUlUTcpM="
